apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      version: "34.0.0"
  values:
    service:
      externalIPs:
        - 192.168.10.100