apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: traefik
spec:
  controller: traefik.io/ingress-controller

# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: traefik
# ---
# apiVersion: source.toolkit.fluxcd.io/v1
# kind: HelmRepository
# metadata:
#   name: traefik
#   namespace: traefik
# spec:
#   interval: 24h
#   url: https://traefik.github.io/charts
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: traefik
#   namespace: traefik
# spec:
#   interval: 30m
#   chart:
#     spec:
#       chart: traefik
#       version: "34.0.0"
#       sourceRef:
#         kind: HelmRepository
#         name: traefik
#         namespace: traefik
#       interval: 12h
#   values:
#     service:
#       externalIPs:
#         - 192.168.10.10
#         - 192.168.10.1